# Generated by Django 3.1 on 2020-08-19 22:19

from django.db import migrations, models
import django.db.models.deletion
import events.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200820_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=events.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventcontentview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='eventcontentview',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(default='Write Down The Content Here'),
        ),
        migrations.DeleteModel(
            name='EventContent',
        ),
        migrations.DeleteModel(
            name='EventContentView',
        ),
        migrations.AddField(
            model_name='images',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
