# Generated by Django 3.1 on 2020-08-19 22:37

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200820_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.BooleanField()),
                ('image', models.ImageField(upload_to=events.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
