# Generated by Django 3.1 on 2020-08-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200820_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Enter The Title', max_length=100),
        ),
    ]
